version: '3.4'
services:
  web:
    image: nginx:stable-alpine
    container_name: web
    depends_on:
      - markaspot
    networks:
     - drupal
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      -  app:/app/data
    ports:
      - 80:80
  markaspot:
    image: markaspot/markaspot:latest
    container_name: markaspot
    environment:
      VIRTUAL_HOST: 'web'
      PHP_MEMORY_LIMIT: -1
      XDEBUG_ENABLED: 0
      MARKASPOT_MARIADB_SERVICE_HOST: 'db'
      DRUPAL_DATABASE_PORT: '3306'
      DRUPAL_DATABASE_NAME: 'drupal'
      DRUPAL_DATABASE_USERNAME: 'drupal'
      DRUPAL_DATABASE_PASSWORD: 'drupal'
      DRUPAL_HASH_SALT: 'SET-IT'
      COMPOSER_MEMORY_LIMIT: '-1'
    restart: on-failure
    # Share the project into the container for local development. Comment out
    # this line to test the production-ready pre-built container codebase.
    # volumes: ['.:/app/data:rw,delegated']
    volumes:
      - .:/app/data
    depends_on:
      - db
    networks:
      - drupal
  db:
    image: mariadb:10
    container_name: db
    environment:
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    #restart: on-failure
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      drupal:
        aliases:
          - db
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db
    networks:
      - drupal

networks:
  drupal:
volumes:
  app:
  db_data:
