services:
  web:
    image: nginx:stable-alpine
    container_name: web
    depends_on:
      - markaspot
    networks:
     - drupal
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app/data
    ports:
      - 80:80
  markaspot:
    image: markaspot/markaspot:latest
    container_name: markaspot
    environment:
      VIRTUAL_HOST: 'web'
      PHP_MEMORY_LIMIT: 1G
      XDEBUG_ENABLED: 0
      MARKASPOT_MARIADB_SERVICE_HOST: 'db'
      DRUPAL_DATABASE_PORT: '3306'
      DRUPAL_DATABASE_NAME: 'drupal'
      DRUPAL_DATABASE_USERNAME: 'drupal'
      DRUPAL_DATABASE_PASSWORD: 'drupal'
      DRUPAL_HASH_SALT: 'SET-IT'
      COMPOSER_MEMORY_LIMIT: '-1'
    restart: on-failure
    # Share the project into the container for local development. Comment out
    # this line to test the production-ready pre-built container codebase.
    # volumes: ['.:/app/data:rw,delegated']
    volumes:
      - .:/app/data
      - ./conf/php.ini:/usr/local/etc/php/conf.d/99-custom.ini
    depends_on:
      - db
    networks:
      - drupal
  db:
    image: mariadb:11
    container_name: db
    environment:
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: 'drupal'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MARIADB_MYSQL_LOCALHOST_USER: 'true'
      MARIADB_MYSQL_LOCALHOST_GRANTS: 'ALL'
      MARIADB_DISABLE_MYSQLD_SAFE: 'true'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      drupal:
        aliases:
          - db
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db
    networks:
      - drupal
  ui:
    image: markaspot/markaspot-ui-base:v1.1.0
    container_name: ui
    environment:
      - GEOREPORT_API_KEY=12841525e0ebd
      - NUXT_API_BASE=http://web
      - NUXT_GEOREPORT_API_BASE=https://localhost
      - BASE_PATH=/
    depends_on:
      - markaspot
    networks:
      - drupal
    ports:
      - "3000:3000"

networks:
  drupal:
    driver: bridge
volumes:
  app:
  db_data:
