<?php
/**
 * @file
 * fontawesome.module
 * Drupal integration with Font Awesome, the iconic font for use with Bootstrap.
 */

define('MARKASPOT_FONT_LIBRARY', 'markaspot-font');
define('MARKASPOT_FONT_NAME', 'Markaspot Font');
define('MARKASPOT_FONT_URL', 'https://github.com/markaspot/markaspot-font');
define('MARKASPOT_FONT_DOWNLOAD_URL', 'https://github.com/markaspot/markaspot-font/archive/master.zip');
define('MARKASPOT_FONT_PREFIX', 'sicon-');

/**
 * Implements hook_libraries_info().
 */
function markaspot_font_libraries_info() {
  $libraries[MARKASPOT_FONT_LIBRARY] = array(
    'version callback' => 'markaspot_font_version_callback',
    'name' => MARKASPOT_FONT_NAME,
    'files' => array(
      'css' => array(
        'style.css',
      ),
    ),
  );
  return $libraries;
}

function markaspot_font_version_callback() {
  return TRUE;
}

/**
 * Implements hook_preprocess_page().
 *
 * Purposefully only load on page requests and not hook_init(). This is
 * required so it does not increase the bootstrap time of Drupal when it isn't
 * necessary.
 */
function markaspot_font_preprocess_page() {
  libraries_load(MARKASPOT_FONT_LIBRARY);
}

/**
 * Implements hook_icon_providers().
 */
function markaspot_font_icon_providers() {
  $providers[MARKASPOT_FONT_LIBRARY] = array(
    'title' => MARKASPOT_FONT_NAME,
    'url' => MARKASPOT_FONT_URL,
  );
  return $providers;
}

/**
 * Implements hook_icon_bundle_configure().
 */
function markaspot_font_icon_bundle_configure(&$settings, &$form_state, &$complete_form) {
  $bundle = $form_state['bundle'];
  if ($bundle['provider'] === MARKASPOT_FONT_LIBRARY) {
    $settings['tag'] = array(
      '#type' => 'select',
      '#title' => t('HTML Markup'),
      '#description' => t('Choose the HTML markup tag that @fontawesome icons should be created with. Typically, this is a %tag tag, however it can be changed to suite the theme requirements.', array(
        '@fontawesome' => MARKASPOT_FONT_NAME,
        '%tag' => '<' . $bundle['settings']['tag'] . '>',
      )),
      '#options' => drupal_map_assoc(array('i', 'span', 'div')),
      '#default_value' => $bundle['settings']['tag'],
    );
  }
}

/**
 * Implements hook_icon_bundles().
 *
 * @todo Extract icons from CSS or JSON file (currently not possible).
 */
function markaspot_font_icon_bundles() {
  $bundles[MARKASPOT_FONT_LIBRARY] = array(
    'title' => MARKASPOT_FONT_NAME,
    'provider' => MARKASPOT_FONT_LIBRARY,
    'render' => 'sprite',
    'settings' => array(
      'tag' => 'i',
    ),
    'icons' => array(
      'brightness-medium' => 'brightness-medium',
      'remove' => 'remove',
      'bullhorn' => 'bullhorn',
      'droplet' => 'droplet',
      'location2' => 'location2',
      'location' => 'location',
      'office' => 'office',
      'bubbles2' => 'bubbles2',
      'bug' => 'bug',
      'leaf' => 'leaf',
      'lab' => 'lab',
      'car' => 'car',
      'pause' => 'pause',
      'bubbles' => 'bubbles',
      'checkmark' => 'checkmark',
      'play' => 'play',
      'close' => 'close',
      'headphones' => 'headphones',
      'drawer' => 'drawer',
      'sign' => 'sign',
      'tree' => 'tree',
      'wi-fi' => 'wi-fi',
      'warning' => 'warning',
      'info' => 'info',
      'phone' => 'phone',
      'grin' => 'grin',
      'umbrella' => 'umbrella',
      'truck' => 'truck',
      'exclamation-sign' => 'exclamation-sign',
      'road' => 'road',
      'medkit' => 'medkit',
      'heart' => 'heart',
      'envelope' => 'envelope',
      'sun' => 'sun',
      'fire-extinguisher' => 'fire-extinguisher',
      'thumbs-up' => 'thumbs-up',
      'thumbs-down' => 'thumbs-down',
      'bell' => 'bell',
      'twitter' => 'twitter',
      'facebook' => 'facebook',
      'heart-outline' => 'heart-outline',
      'directions' => 'directions',
      'feather' => 'feather',
      'share' => 'share',
      'bell2' => 'bell2',
      'moon' => 'moon',
      'new' => 'new',
      'shuffle' => 'shuffle',
      'switch' => 'switch',
      'cc' => 'cc',
      'pedestrian' => 'pedestrian',
      'bike' => 'bike',
      'motobike' => 'motobike',
      'skate' => 'skate',
      'trash' => 'trash',
      'headphone2' => 'headphone2',
      'camera' => 'camera',
      'minus-circle' => 'minus-circle',
      'remove-circle' => 'remove-circle',
      'check-circle' => 'check-circle',
      'info-circle' => 'info-circle',
      'remove-circle-o' => 'remove-circle-o',
      'check-circle-o' => 'check-circle-o',
      'eye' => 'eye',
      'warning2' => 'warning2',
      'wrench' => 'wrench',
      'flash' => 'flash',
      'building' => 'building',
      'fighter-jet' => 'fighter-jet',
      'recycle' => 'recycle',
      'bridge' => 'bridge',
      'graffiti' => 'graffiti',
      'wheelchair' => 'wheelchair',
    ),
  );
  return $bundles;
}

/**
 * Implements hook_preprocess_icon_RENDER_HOOK().
 */
function markaspot_font_preprocess_icon_sprite(&$variables) {
  $bundle = &$variables['bundle'];
  if ($bundle['provider'] === MARKASPOT_FONT_LIBRARY) {

    $icon = &$variables['icon'];
    $classes = &$variables['attributes']['class'];
    $settings = $variables['bundle']['settings'];

    $settings['prefix'] = 'icon-';
    // Add an identifier class for this bundle.
    $classes[] = $settings['prefix'] . $icon;
  }
}