<?php

/**
 * @file
 * Cloudmade OSM widget and formaters for Geolocation.
 */

/**
 * Implements hook_field_formatter_info().
 */
function geolocation_cloudmade_osm_field_formatter_info() {
  global $base_url;
  return array(
    'geolocation_cloudmade_osm_static' => array(
      'label' => t('Static Cloudmade Map'),
      'field types' => array('geolocation_latlng'),
      'settings' => array(
        'map_dimensions' => '300x300',
        'map_imageformat' => 'png',
        'marker_icon' => $base_url . '/profiles/markaspot/libraries/Leaflet/images/marker-icon.png',
        'map_zoomlevel' => '15',
        'map_style' => '22677',
        'leafletImagePath' => $base_url . '/profiles/markaspot/libraries/Leaflet/images/',
        'cloudmade_api_key' => ''
      ),
    ),
    'geolocation_cloudmade_osm_dynamic' => array(
      'label' => t('Dynamic Cloudmade Leaflet Map'),
      'field types' => array('geolocation_latlng'),
      'settings' => array(
        'map_dimensions' => '300x300',
        'map_zoomlevel' => '15',
        'marker_icon' => $base_url . '/profiles/markaspot/libraries/Leaflet/images/marker-icon.png',
        'map_style' => '22677',
        'leafletImagePath' => $base_url . '/profiles/markaspot/libraries/Leaflet/images/',
        'map_scrollwheel' => FALSE,
        'cloudmade_api_key' => ''

      ),
    ),
  );
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function geolocation_cloudmade_osm_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {

  $display = $instance['display'][$view_mode];
  $type = $display['type'];
  $settings = $display['settings'];

  $element = array();

  // Implement some configuration options.
  // http://code.google.com/intl/en/apis/maps/documentation/staticmaps/
  $element['map_dimensions'] = array(
    '#type' => 'textfield',
    '#title' => t('Map dimensions'),
    '#description' => t('Enter custom map dimensions, default is 300x300.'),
    '#default_value' => $settings['map_dimensions'],
  );

  $element['marker_icon'] = array(
    '#type' => 'textfield',
    '#title' => t('Marker icon'),
    '#description' => t('Set the path to the icon marker you wish to use. Path can be absolute (wicth http://) or relative to the Drupal instalation. If left blank, the default will be used'),
    '#default_value' => $settings['marker_icon'],
  );
  $element['cloudmade_api_key'] = array (
    '#type' => 'textfield',
    '#title' => t('Cloudmade API Key'),
    '#description' => t('Insert your API Key here'),
    '#default_value' => $settings['cloudmade_api_key'],
  );
  // Image format is used only for static maps.
  switch ($type) {
    case 'geolocation_cloudmade_osm_static':
      $element['map_imageformat'] = array(
        '#type' => 'select',
        '#title' => t('Image format'),
        '#options' => array(
          'png' => '8-bit PNG (default)',
          'png32' => '32-bit PNG',
          'gif' => 'GIF',
          'jpg' => 'JPEG'
        ),
        '#description' => t('Choose an Image Format. jpg and jpg-baseline typically provide the smallest image size, though they do so through "lossy" compression which may degrade the image. gif, png8 and png32 provide lossless compression.'),
        '#default_value' => $settings['map_imageformat'],
      );
      break;

    case 'geolocation_cloudmade_osm_dynamic':
      // if supported, don't know yet
      $element['map_scrollwheel'] = array(
        '#type' => 'checkbox',
        '#title' => t('Scroll Zoom'),
        '#description' => t('By default zooming is done with double click and/or using the map controls to avoid interrupting the normal window scroll. It can optionally be enabled here.'),
        '#default_value' => $settings['map_scrollwheel'],
      );
      break;
  }

  $element['map_style'] = array(
    '#type' => 'textfield',
    '#title' => t('Map Style'),
    '#description' => t('Enter a map style-id.'),
    '#default_value' => $settings['map_style'],
  );

  $element['leafletImagePath'] = array(
    '#type' => 'textfield',
    '#title' => t('Leaflet Image Path'),
    '#description' => t('Set the image path of your leaflet library (needed with compressed javascript on production sites, see https://github.com/Leaflet/Leaflet/issues/766'),
    '#default_value' => $settings['leafletImagePath'],
  );

  $element['map_zoomlevel'] = array(
    '#type' => 'select',
    '#title' => t('Zoom level'),
    '#options' => array(
      '1' => '1',
      '2' => '2',
      '3' => '3',
      '4' => '4',
      '5' => '5',
      '6' => '6',
      '7' => '7 (default)',
      '8' => '8',
      '9' => '9',
      '10' => '10',
      '11' => '11',
      '12' => '12',
      '13' => '13',
      '14' => '14',
      '15' => '15',
      '16' => '16',
      '17' => '17',
      '18' => '18',
      '19' => '19',
    ),
    '#description' => t('Choose a custom zoom level - the higher the number the closer. <em>High zoom warning:</em> Google might not return images for any combination of Map Type and Zoom Level.'),
    '#default_value' => $settings['map_zoomlevel'],
  );

  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function geolocation_cloudmade_osm_field_formatter_settings_summary($field, $instance, $view_mode) {

  $display = $instance['display'][$view_mode];
  $type = $display['type'];
  $settings = $display['settings'];
  $summary = '<strong>Map:</strong> ' . $settings['map_dimensions'];
  switch ($type) {
    case 'geolocation_cloudmade_osm_static':
      $summary .= ' (' . $settings['map_imageformat'] . ')';
      $summary .= '<br />';
      break;

    case 'geolocation_cloudmade_osm_dynamic':
      $summary .= '<br />';
      $scrl = $settings['map_scrollwheel'] ? t('Yes') : t('No');
      $summary .= '<strong>Scrollable:</strong> ' . $scrl . '<br />';
      break;
  }
  $summary .= '<strong>Cloudmade API Key:</strong> ' . $settings['cloudmade_api_key'] . '<br />';
  $summary .= '<strong>Style-Id:</strong> ' . $settings['map_style'] . '<br />';
  $summary .= '<strong>Zoom:</strong> ' . $settings['map_zoomlevel'];
  if (!empty($settings['marker_icon'])) {
    $vars = array(
      'path' => $settings['marker_icon'],
    );
    $summary .= '<br /><strong>Icon:</strong> ' . theme('image', $vars);
  }
  return $summary;
}

/**
 * Implements hook_field_formatter_view().
 */
function geolocation_cloudmade_osm_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $settings = $display['settings'];
  $element = array();

  switch ($display['type']) {

    case 'geolocation_cloudmade_osm_static':
      foreach ($items as $delta => $item) {
        $query = array(
          //'sensor' => 'false',
          'zoom' => $settings['map_zoomlevel'],
          'size' => $settings['map_dimensions'],
          'format' => $settings['map_imageformat'],
          'styleid' => $settings['map_style'],
          'center' => $item['lat'] . ',' . $item['lng'],
          'markers' => 'size:mid|color:red|' . $item['lat'] . ',' . $item['lng'],
        );
        if ($settings['marker_icon']) {
          $path = file_create_url($settings['marker_icon']);
          $query['markers'] = 'icon:' . $path . '|' . $query['markers'];
        }
        $variables = array(
          'path' => url('http://staticmaps.cloudmade.com/'.$settings['cloudmade_api_key'].'/staticmap?', array('query' => $query)),
          'alt' => 'Geolocation',
          'attributes' => array('class' => 'geolocation-cloudmade-osm-static'),
        );
        $map_img = theme('image', $variables);
        $element[$delta]['#markup'] = '<div>' . $map_img . '</div>';
      }
      break;

    case 'geolocation_cloudmade_osm_dynamic':
      $info = entity_get_info($entity_type);
      $key = isset($info['entity keys']['name']) ? $info['entity keys']['name'] : $info['entity keys']['id'];
      $eid = $entity->$key;

      foreach ($items as $delta => $item) {

        $width = strtok($settings['map_dimensions'], 'x') . "px";
        $height = strtok('') . "px";

        $id = 'geolocation-cloudmade-osm-dynamic-' . 'e_' . $eid . 'i_' . $instance['id'] . '-d_' . $delta;
        $map_element['cloudmade-osm'] = array(
          '#prefix' => '<div id="' . $id . '" class="geolocation-map geolocation-cloudmade-osm-dynamic" ' . ' style="width:' . htmlentities($width) . ';height:' . htmlentities($height) . ';">',
          '#suffix' => '</div>',
        );

        // Attach CSS and JS files via FAPI '#attached'.
        $map_element['cloudmade-osm']['#attached']['css'][] = drupal_get_path('module', 'geolocation_cloudmade_osm') . '/geolocation_cloudmade_osm.css';
          // Attach CSS and JS files via FAPI '#attached'.


        // Wont work:
        // $map_element['cloudmade-osm']['#attached']['css'][] = array(
        //   'http://cdn.leafletjs.com/leaflet-0.4.4/leaflet.css',
        //   'type' => 'external'
        // );


        $map_element['cloudmade-osm']['#attached']['js'][] = array(
          'data' => drupal_get_path('profile','markaspot') . '/libraries/Leaflet/leaflet.js',
          'type' => 'file',
          //'scope' => 'footer',
        );

        $map_element['cloudmade-osm']['#attached']['js'][] = array(
          'data' => drupal_get_path('module', 'geolocation_cloudmade_osm') . '/geolocation_cloudmade_osm_dynamic_formatter.js',
          'type' => 'file',
          'scope' => 'footer',
        );
        // Add each delta to the settings array.
        $data = array(
          'formatters' => array(
            'e_' . $eid . 'i_' . $instance['id'] => array(
              "settings" => $settings,
              "deltas" => array(
                'd_' . $delta => array(
                  'lat' => $item['lat'],
                  'lng' => $item['lng'],
                ),
              ),
            ),
          ),
        );

        $map_element['cloudmade-osm']['#attached']['js'][] = array(
          'data' => array('geolocationCloudmadeOsm' => $data),
          'type' => 'setting',
        );

        $element[$delta] = $map_element;

      }
      break;

  }
  return $element;
}

/**
 * Implements hook_field_widget_info().
 */
function geolocation_cloudmade_osm_field_widget_info() {
  return array(
    'geolocation_cloudmade-osm' => array(
      'label' => t('Cloudmade'),
      'field types' => array('geolocation_latlng'),
    ),
  );
}

/**
 * Implements hook_field_widget_settings_form().
 */
function geolocation_cloudmade_osm_field_widget_settings_form($field, $instance) {
  $widget = $instance['widget'];
  $settings = $widget['settings'];
  // $form['bing_api_key'] = array(
  //   '#type' => 'textfield',
  //   '#title' => t('Bing Geolocation API Key'),
  //   '#description' => t('This module makes use of the bing geolocation api. Check http://msdn.microsoft.com/en-us/library/ff701713.aspx for more information. You have to sign up to obtain an API. Sart here: http://msdn.microsoft.com/en-us/library/ff428642.aspx '),
  //   '#default_value' => isset($settings['bing_api_key']) ? $settings['bing_api_key'] : FALSE,
  // );
  $form['nominatimEmail'] = array(
    '#type' => 'textfield',
    '#title' => t('Nominatim E-Mail for problem reporting'),
    '#description' => t('If you are making large numbers of request please include a valid email address or alternatively include your email address as part of the User-Agent string. This information will be kept confidential and only used to contact you in the event of a problem, see Usage Policy for more details.'),
    '#default_value' => isset($settings['nominatimEmail']) ? $settings['nominatimEmail'] : FALSE,
  );
  $form['leafletImagePath'] = array(
    '#type' => 'textfield',
    '#title' => t('Leaflet Image path'),
    '#description' => t('Set the image path of your leaflet library (needed with compressed javascript on production sites, see https://github.com/Leaflet/Leaflet/issues/766'),
    '#default_value' => isset($settings['leafletImagePath']) ? $settings['leafletImagePath'] : FALSE,
  );
  $form['scrollwheel'] = array(
    '#type' => 'checkbox',
    '#title' => t('Scroll Zoom'),
    '#description' => t('By default zooming is done with double click and/or using the map controls to avoid interrupting the normal window scroll. It can optionally be enabled here.'),
    '#default_value' => isset($settings['scrollwheel']) ? $settings['scrollwheel'] : FALSE,
  );
  $form['marker_draggable'] = array(
    '#type' => 'checkbox',
    '#title' => t('Draggable Marker'),
    '#description' => t('Enabling this will allow the user to darg/drop the marker to select a location.'),
    '#default_value' => isset($settings['marker_draggable']) ? $settings['marker_draggable'] : FALSE,
  );

  return $form;
}

/**
 * Implements hook_field_widget_form().
 */
function geolocation_cloudmade_osm_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {

  $id = $instance['id'] . '-' . $delta;
  // default NULL is not valid, so home is where the heart is ...
  $lat_value = isset($items[$delta]['lat']) ? $items[$delta]['lat'] : '50.93';
  $lng_value = isset($items[$delta]['lng']) ? $items[$delta]['lng'] : '6.96';
  $element += array(
    '#delta' => $delta,
  );

  switch ($instance['widget']['type']) {

    case 'geolocation_cloudmade-osm':
      $element['address'] = array(
        '#type' => 'item',
        '#title' => $element['#title'],
        '#prefix' => '<div id="geolocation-address-' . $id . '" class="geolocation-address">',
        '#suffix' => '</div>',
        '#required' => $instance['required'],
      );
      $element['address']['field'] = array(
        '#type' => 'textfield',
        '#maxlength' => 120,
        '#size' => 50
      );
      $element['address']['geocode'] = array(
        '#prefix' => '<span id="geolocation-address-geocode-' . $id . '" class="geolocation-address-geocode">',
        '#suffix' => '</span>',
        '#markup' => t('Get location'),
      );
      $element['help'] = array(
        '#prefix' => '<div id="geolocation-help-' . $id . '" class="geolocation-help">',
        '#suffix' => '</div>',
        '#markup' => t('Enter an address / location in the textfield or you can also click on the map to set a marker'),
      );
      $element['cloudmade-osm'] = array(
        '#prefix' => '<div id="geolocation-map-' . $id . '" class="geolocation-map" style="width:100%;height:400px;">',
        '#suffix' => '</div>',
      );
      // Presentational item.
      $element['latitem'] = array(
        '#type' => 'item',
        '#title' => t('Latitude:'),
        '#prefix' => '<div id="geolocation-lat-item-' . $id . '" class="geolocation-lat-item">',
        '#suffix' => '</div>',
        '#markup' => '<span class="geolocation-lat-item-value">' . $lat_value . '</span>',
        '#required' => $instance['required'],
      );
      $element['lat'] = array(
        '#type' => 'hidden',
        '#prefix' => '<div id="geolocation-lat-' . $id . '" class="geolocation-lat">',
        '#suffix' => '</div>',
        '#default_value' => $lat_value,
      );
      // Presentational item.
      $element['lngitem'] = array(
        '#type' => 'item',
        '#title' => t('Longitude:'),
        '#prefix' => '<div id="geolocation-lng-item-' . $id . '" class="geolocation-lng-item">',
        '#suffix' => '</div>',
        '#markup' => '<span class="geolocation-lng-item-value">' . $lng_value . '</span>',
        '#required' => $instance['required'],
      );
      $element['lng'] = array(
        '#type' => 'hidden',
        '#prefix' => '<div id="geolocation-lng-' . $id . '" class="geolocation-lng">',
        '#suffix' => '</div>',
        '#default_value' => $lng_value,
      );
      $element['remove'] = array(
        '#prefix' => '<div id="geolocation-remove-' . $id . '" class="geolocation-remove"><span>',
        '#suffix' => '</span></div>',
        '#markup' => t('Remove'),
      );

      // Attach CSS and JS files via FAPI '#attached'.
      $element['cloudmade-osm']['#attached']['css'][] = drupal_get_path('module', 'geolocation_cloudmade_osm') . '/geolocation_cloudmade_osm.css';
        // Attach CSS and JS files via FAPI '#attached'.


      // Wont work:
      // $map_element['cloudmade-osm']['#attached']['css'][] = array(
      //   'http://cdn.leafletjs.com/leaflet-0.4.4/leaflet.css',
      //   'type' => 'external'
      // );


      $element['cloudmade-osm']['#attached']['js'][] = array(
        'data' => drupal_get_path('profile','markaspot') . '/libraries/Leaflet/leaflet.js',
        'type' => 'file',
        'scope' => 'footer',
      );

      $element['cloudmade-osm']['#attached']['js'][] = array(
        'data' => drupal_get_path('module', 'geolocation_cloudmade_osm') . '/geolocation_cloudmade_osm_widget.js',
        'type' => 'file',
        'scope' => 'footer',
      );

      // Make defaults available as javascript settings. In JS files use:
      // Drupal.settings.mapDefaults.lat
      $map_defaults_lat = ($lat_value) ? $lat_value : '';
      $map_defaults_lng = ($lng_value) ? $lng_value : '';
      $map_defaults = array(
        $id => array(
          'lat' => $map_defaults_lat,
          'lng' => $map_defaults_lng,
        ),
      );
      $data = array(
        'defaults' => $map_defaults,
        'settings' => $instance['widget']['settings'],
      );
      $element['cloudmade-osm']['#attached']['js'][] = array(
        'data' => array('geolocation' => $data),
        'type' => 'setting',
      );

      $element['#element_validate'] = array('geolocation_cloudmade_osm_field_widget_validate');

      break;
  }
  return $element;
}

/**
 * Validation handler for geolocation_cloudmade_osm_field_widget_form().
 */
function geolocation_cloudmade_osm_field_widget_validate($element, &$form_state, $form) {
  if ($element['#required']) {
    if (!$element['lat']['#value'] || !$element['lng']['#value']) {
      form_error($element, t('!name field is required.', array('!name' => $element['#title'])));
    }
  }
  else {
    switch (TRUE) {
      case $element['lng']['#value'] && !$element['lat']['#value']:
        form_error($element, t('!name field is incomplete, latitude value is missing.', array('!name' => $element['#title'])));
        break;

      case !$element['lng']['#value'] && $element['lat']['#value']:
        form_error($element, t('!name field is incomplete, longitude value is missing.', array('!name' => $element['#title'])));
        break;
    }
  }
}

/**
 * Implements hook_field_widget_error().
 */
function geolocation_cloudmade_osm_field_widget_error($element, $error, $form, &$form_state) {
  switch ($error['error']) {
    case 'geolocation_invalid_lat':
    case 'geolocation_invalid_lng':
      form_error($element, $error['message']);
      break;
  }
}
