<?php

/**
 * This module provides a block of unpublished nodes (reports)
 *
 * @author Holger Kreis - holger@markaspot.org
 */

// After you learn Form API in Chapter 5, you'll be able to
// make these settings configurable.
define('MAS_NODE_TYPE', 'report');
define('MAS_LIST_COUNT', 5);
define('MAS_DATE_FORMAT', 'F d, Y');

/**
 * Returns a list of blog entries.
 *
 * @param $number
 *   The number of blog entries to return.
 * @return
 *   A result set object containing the list of blog entries.
 */
function markaspot_unpublished_list($number) {
  // Use the Database API to retrieve our data.
  // @see http://drupal.org/node/310069
  $query = db_select('node', 'n')
    ->fields('n', array('nid', 'title', 'created', 'uid'))
    ->condition('type', MAS_NODE_TYPE)
    ->condition('status', 0)
    ->orderBy('created', 'DESC')
    ->range(0, $number)
    ->addTag('node_access')
    ->execute();

  return $query;
}

/**
 * Implements hook_block_info().
 */
function markaspot_unpublished_block_info() {
  $blocks = array();

  // The array key defines the $delta parameter used in all
  // other block hooks.
  $blocks['recent'] = array(
    // The name of the block on the blocks administration page.
    'info' => t('Mas Recent reports unpublished'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * Third draft!
 *
 * @pararm $delta
 *   The name of the requested block.
 */
function markaspot_unpublished_block_view($delta = '') {
  // Create an empty block.
  $block = array(
    'subject' => '',
    'content' => '',
  );

  // Check which block is being requested.
  if ($delta == 'recent') {
    // Set the block title.
    $block['subject'] = t('Recent MaS-reports');

    // Check if the user can access content.
    if (user_access('access content')) {
      // Retrieve the most recent nodes.
      $result = markaspot_unpublished_list(MAS_LIST_COUNT);

      // Create links for each blog entry.
      $items = array();
      foreach ($result as $node) {
        $items[] = array(
          'data' => array(
            '#theme' => 'markaspot_unpublished_block_item',
            '#node' => $node,
          ),
          'class' => array('node-' . $node->nid),
        );
      }

      if (!empty($items)) {
        // Theme the list of blog entries.
        $block['content']['list'] = array(
          '#theme' => 'item_list__markaspot_unpublished',
          '#title' => t('This block shows reports not yet published'),
          '#items' => $items,
          '#pre_render' => array('markaspot_unpublished_item_list_child_render'),
        );
        // Add a link to the full list of blog entries.
        $block['content']['more'] = array(
          '#theme' => 'more_link',
          '#url' => 'unpublished',
          '#title' => t('Read the latest unpblished reports.'),
        );
        // Add a CSS file to style the block.
       //$block['content']['#attached']['css'][] = drupal_get_path('module', 'markaspot_unpublished') . '/markaspot_unpublished.css';
      }
    }
  }

  return $block;
}

/**
 * Render the child elements of theme_item_list() before its data is themed.
 */
function markaspot_unpublished_item_list_child_render($elements) {
  foreach (array_keys($elements['#items']) AS $key) {
    // Take the renderable array that we set in markaspot_unpublished_block_view() and
    // render it into the string that theme_item_list() expects.
    if (is_array($elements['#items'][$key]['data'])) {
      $elements['#items'][$key]['data'] = drupal_render($elements['#items'][$key]['data']);
    }
  }
  return $elements;
}

/**
 * Implements hook_theme().
 */
function markaspot_unpublished_theme($existing, $type, $theme, $path) {
  return array(
    'markaspot_unpublished_block_item' => array(
      'variables' => array(
        'node' => NULL,
      ),
      'template' => 'mas-unpublished-block-item',
    ),
  );
}

/**
 * Preprocesses single blog block item variables.
 */
function template_preprocess_markaspot_unpublished_block_item(&$variables) {
  $node = $variables['node'];

  // Create a renderable array for the title.
  $variables['title'] = array(
    '#type'  => 'link',
    '#title' => $node->title,
    '#href'  => 'list-unpublished',
  );

  // Format the creation date of the node.
  $variables['created'] = $node->created;
  $variables['date'] = format_date($node->created, 'custom', MAS_DATE_FORMAT);

  // Load the account object with the node's creator and store in a variable for
  // themer convenience.
  $variables['user'] = user_load($node->uid);
  // Theme the username.
  $variables['name'] = theme('username', array('account' => $variables['user']));
}
