<?php

/**
 * @file
 * provides content and text mapping and creating nodes from tweets
 * Most of the code taken from Twitter Import Module by fabianderijk http://drupal.org/user/278745
 * http://drupal.org/project/twitter_import
 */


/**
 * Implements hook_cron().
 */
function markaspot_tweet311_cron() {
  _markaspot_tweet311_import_terms();
}

function _markaspot_tweet311_import_manual() {
  _markaspot_tweet311_import_terms();
  drupal_goto('admin/config/system/mark_a_spot/');
}
/**
 *
 * Function that imports the tweets from the term search
 */
function _markaspot_tweet311_import_terms() {
  $term = variable_get('markaspot_twittername', '');
  if (!empty($term)) {
    $term = urlencode($term);
    $url = 'http://search.twitter.com/search.json?q=' . $term . '&include_entities=1&show_user=true&result_type=mixed&rpp=50';
    $data = drupal_http_request($url);
    _markaspot_tweet311_create_content($data, TRUE);
  }
}


function _markaspot_tweet311_create_content($data, $usercheck = FALSE) {
  if ($data->code < 400 && !empty($data->data)) {
    $results = drupal_json_decode($data->data);
    $varusers = variable_get('markaspot_tweet311_user', '');
    $importuser = explode(',', drupal_strtolower($varusers));

    if (!empty($results)) {
      foreach ($results['results'] AS $tweet) {

        if ($tweet['from_user'] != $importuser || !$usercheck) {
          $safeuser = explode(',', drupal_strtolower(variable_get('markaspot_tweet311_term_safe_user', '')));
          // Checking if tweet is already imported
          $query = db_select('twitter_import', 'ti');
          $query->condition('ti.tweet_id', $tweet['id_str'])
            ->fields('ti', array('id'))
            ->range(0, 1);
          $result = $query->execute();
          $num_rows = $query->countQuery()->execute()->fetchField();
          if (empty($num_rows)) {
            if (in_array(drupal_strtolower($tweet['from_user']), $safeuser) || in_array(drupal_strtolower($tweet['from_user']), $importuser)) {
              $status = 1;
            }
            else {
              $status = 0;
            }
            
            $fid = 0;
            
            // create User
            $user = _twitter_create_user_from_tweet($tweet);

            $id = db_insert('twitter_import')
              ->fields(array(
                'tweet_id' => $tweet['id_str'],
                'user' => $tweet['from_user'],
                'tweet' => $tweet['text'],
                'created' => strtotime($tweet['created_at']),
                'data' => drupal_json_encode($tweet),
                'status' => $status,
                'source' => $tweet['source'],
                'fid' => $fid,
              ))
              ->execute();
            // mapping tweet to node
            // _markaspot_tweet311_map_node($tweet, $user);

            // only import tweet if tweet applies to a known service
            $node = _markaspot_tweet311_map_node($tweet, $user);
            if (isset($node)) {
              node_save($node);
              drupal_set_message(t("Tweet imported with Hashtag"));
            } else {
              drupal_set_message(t("Tweet found but no matching Hashtag"));
            }

          }
        }
      }
    }
  }
  else {
    drupal_set_message(check_plain(t('Error while importing Tweets; Code: ') . $data->code), 'error');
  }
}


/**
 * Get the profile pic from twitter if not already downloaded and not older than 1 week
 */
function _markaspot_tweet311_get_profile_pic($userid, $picurl) {
  $fid = FALSE;

  $filename = $userid . '.png';
  $folder = 'markaspot_tweet311_profile_pics/';
  $complete = $folder . $filename;

  $folderuri = file_build_uri($folder);
  $uri = file_build_uri($complete);
  $path = drupal_realpath($uri);

  if (!file_exists($path) || filemtime($path) < (REQUEST_TIME - 604800)) {
    $data = @file_get_contents($picurl);
    drupal_mkdir($folderuri);
    $file = file_save_data($data, $uri, FILE_EXISTS_REPLACE);
    $fid = $file->fid;
  }
  else {
    $fid = _markaspot_tweet311_get_fid_from_uri($uri);
  }

  if (isset($fid)) {
    return $fid;
  }

  return;
}


function _markaspot_tweet311_get_fid_from_uri($uri) {
  $query = db_select('file_managed', 'fm');
  $query->condition('fm.uri', $uri)
    ->fields('fm', array('fid'))
    ->range(0, 1);
  $result = $query->execute();
  foreach ($result as $record) {
    return $record->fid;
  }
  return FALSE;
}


function _markaspot_tweet311_twitterify($ret, $target = '_blank') {
  $ret = preg_replace("#(^|[\n ])([\w]+?://[\w]+[^ \"\n\r\t< ]*)#", "\\1<a href=\"\\2\" target=\"" . $target . "\">\\2</a>", $ret);
  $ret = preg_replace("#(^|[\n ])((www|ftp)\.[^ \"\t\n\r< ]*)#", "\\1<a href=\"http://\\2\" target=\"" . $target . "\">\\2</a>", $ret);
  $ret = preg_replace("/@(\w+)/", "<a href=\"http://www.twitter.com/\\1\" target=\"" . $target . "\">@\\1</a>", $ret);
  $ret = preg_replace("/#(\w+)/", "<a href=\"http://search.twitter.com/search?q=\\1\" target=\"" . $target . "\">#\\1</a>", $ret);
  return $ret;
}

function markaspot_tweet311_load_tweet($tid) {
  $query = db_select('twitter_import', 'ti')
    ->fields('ti', array('tweet', 'user'))
    ->condition('ti.id', $tid)
    ->range(0, 1);
  
  $result = $query->execute();
  foreach ($result as $record) {
    return $record;
  }
}


/**
 * Retrieving the tid out of hashtag or service code by hash
 *
 * @param $tweet
 *  The tweet imported.
 * @return object $taxonomy_term
 *  The taxonomy object
 */

function _markaspot_get_taxonomy($tweet){

  // Getting all servicecodes or hashes 
  $taxonomies = taxonomy_get_tree(2, $parent = 0, $max_depth = 1, $load_entities = TRUE);

  foreach ($taxonomies as $taxonomy_term) {
    if (variable_get('markaspot_tweetSearch') == 1) {
        $services[] = '#'.$taxonomy_term->field_category_id['und'][0]['value'];  
    } else {
      if (isset($taxonomy_term->field_hash['und'][0]['value'])) {

        $service_hashes = explode(',', $taxonomy_term->field_hash['und'][0]['value']);
        foreach ($service_hashes as $service) {
          $services[] = '#'.trim($service); 
        }
      } 
    }
  }

  // checking the incoming mentions of citizens for matching available services
  if (!isset($services)) {
    return false;
  }
  foreach ($services as $service) { 
    
    if (strpos($tweet['text'], $service) !== FALSE) {
      $service_found = substr($service, 1);


      // matching now service_code or hash-tag with taxonomy term ID (tid)
      $query = new EntityFieldQuery();

      $query
      ->entityCondition('entity_type', 'taxonomy_term', '=')
      ->propertyCondition('vid', 2);

      // Switch Service Code or Service Name

      if (variable_get('markaspot_tweetSearch') == 1) {
        $query
        ->fieldCondition('field_category_id', 'value', array($service_found), '=');
      } else {
        $query
        ->fieldCondition('field_hash', 'value', '%'.$service_found.'%', 'LIKE');
        // ->fieldCondition('field_hash', 'value', array($service_found), 'LIKE');
      }
      $taxonomy_found = $query->execute();
      $tid = array_keys($taxonomy_found["taxonomy_term"]);

      // Load term as object from id
      $taxonomy_term_found = taxonomy_term_load($tid[0]);
      return $taxonomy_term_found;
    }
  }
}


/**
 * Mapping a georeport service request to drupal node.
 *
 * @param array $tweet
 *  The tweet imported.
 * @return object $node
 *  The node object
 */

function _markaspot_tweet311_map_node($tweet, $twitter_user) {

  $node->language = 'und'; // language - neutral


  // Loading the taxonomy term by requested hashed #service_code or #hash-tag
  $service = _markaspot_get_taxonomy($tweet);

  
  if (isset($service->name)) {
    $node->title = $service->name;
    $node->field_category[$node->language][0]['tid'] = $service->tid;

    $node->uid = $twitter_user->uid;
    $node->created = time();
    $node->modified = time();

    if(isset($tweet['entities']['media'])){
      $fid = _markaspot_tweet311_get_tweet_pic($tweet['entities']['media'][0]['media_url']);
      $node->field_image[$node->language][0]['fid'] = $fid;
    }
    
    // applying it to title and it's taxonomyId to field_category
    // All incoming requests get status "open"
    $node->field_status[$node->language][0]['tid'] = 1;

    $node->body[$node->language][0]['value'] = $tweet['text'];
    $node->body[$node->language][0]['format']  = 'filtered_html';

    // Make Requests valid only in the municiple
    $node->field_city[$node->language][0]['value'] = variable_get('markaspot_city');

    $node->field_geo[$node->language][0]['lat'] = (isset($tweet['geo']['coordinates'][0])) ? $tweet['geo']['coordinates'][0] : variable_get('markaspot_ini_lat');
    $node->field_geo[$node->language][0]['lng'] = (isset($tweet['geo']['coordinates'][1])) ? $tweet['geo']['coordinates'][1] : variable_get('markaspot_ini_lng');
    global $base_url;
    $url_parts = parse_url($base_url);
    $node->field_e_mail[$node->language][0]['value'] = 'no-reply@'.$url_parts['host'];
    $node->status = 0;
    $node->is_new = true;
    $node->type = 'report';
  } else {
    $node = null;
  }
  
  return $node;
}


/**
 * Get the profile pic from twitter if not already downloaded and not older than 1 week
 */

function _markaspot_tweet311_get_tweet_pic($picurl) {
  $fid = FALSE;


  $filename = substr(hash('sha256', time()), 0,8) . '.png';
  $folder = 'markaspot_tweet311_tweet_pics/';
  $complete = $folder . $filename;

  $folderuri = file_build_uri($folder);
  $uri = file_build_uri($complete);
  $path = drupal_realpath($uri);

  if (!file_exists($folderuri)) {
    drupal_install_mkdir($folderuri, $mask);
  }  
  if (!file_exists($path) || filemtime($path) < (REQUEST_TIME - 604800)) {
    $data = @file_get_contents($picurl);
    //drupal_mkdir($folderuri);
    $file = file_save_data($data, $uri, FILE_EXISTS_REPLACE);
    $fid = $file->fid;
  }
  else {
    $fid = _markaspot_tweet311_get_fid_from_uri($uri);
  }

  if ($fid) {
    return $fid;
  }

  return $fid;
}

function _twitter_create_user_from_tweet($tweet){

  $username = $tweet['from_user'];
  // Check if user is already registered
  if (!db_query("SELECT COUNT(*) FROM {users} WHERE name = :name", array(':name' => $username))->fetchField()) {
    $newUser = array(
      'name' => $username, 
      'pass' => '',  // note: do not md5 the password
      'mail' => '', 
      'status' => 1, 
      'init' => $username,
      'roles' => array(4)
    );
    $user = user_save(null, $newUser); 
  } else {
    // yes we have $username;
    $user = user_load_by_name(check_plain($username));
  }
  return $user;

}



/**
 * Returns field values as actual entities where possible,
 * also allows selection of individual items to be returned
 */
function field_fetch_field_values($entity_type, $entity, $field_name, $get_delta = NULL, $get_key = NULL) {
  $values = array();
  if (isset($entity->$field_name) && !empty($entity->$field_name)) {
    foreach (field_get_items($entity_type, $entity, $field_name) as $delta => $item) {
      $value = $item;
      $keys = array_keys($item);
      if (count($keys)==1) {
        $key = $keys[0];
        switch ($key) {
          case 'nid':
            $value = array_shift(entity_load('node', array($item[$key])));
            break;
          case 'uid':
            $value = array_shift(entity_load('user', array($item[$key])));
            break;
          case 'tid':
            $value = array_shift(entity_load('taxonomy_term', array($item[$key])));
            break;
          case 'vid':
            $value = array_shift(entity_load('taxonomy_vocabulary', array($item[$key])));
            break;
          case 'value':
            $value = $item['value'];
            break;
        }
      }
      else {
        if ($get_key && isset($item[$get_key])) {
          $value = $item[$get_key];
        }
        elseif (array_key_exists('value', $item)) {
          $value = isset($item['safe_value']) ? $item['safe_value'] : $item['value'];
        }
      }
      $values[$delta] = $value;
    }
  }
  if (is_numeric($get_delta)) {
    return isset($values[$get_delta]) ? $values[$get_delta] : NULL;
  }
  return $values;
}
