<?php

/**
 * Implementation of hook_services_authentication().
 */
function services_open311_oauth_services_authentication_info() {
  return array(
    'file'             => 'services_open311_oauth.inc',
    'title'            => t('OAuth Open311 authentication'),
    'description'      => t('An open protocol to allow secure API authorization'),
    'security_settings' => '_services_open311_oauth_security_settings',
    'default_security_settings' => '_services_open311_oauth_default_security_settings',
    'authenticate_call' => '_services_open311_oauth_authenticate_call',
    'controller_settings' => '_services_open311_oauth_controller_settings',
  );
}
