<?php
/**
 * @file
 * Mark-a-Spot Archive module.
 * This module implements hook_cron to automatically archive reports
 * after a certain period
 */

/**
 * Implements hook_cron().
 */
function markaspot_archive_cron() {

  $period = variable_get('markaspot_logic_archive_days') * 86400;

  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->propertyCondition('status', 1)
    ->propertyCondition('type', array('report'))
    ->propertyCondition('changed', time() - $period, '<=')
    ->fieldCondition('field_status', 'tid', 7)
    ->propertyOrderBy('created', 'DESC');
  $result = $query->execute();

  if ($result) {
    $nodes = node_load_multiple(array_keys($result['node']));

    foreach ($nodes as $node) {
      $node->field_status[LANGUAGE_NONE][0]['tid'] = "8";
      node_save($node);
    }
  }
}
