<?php
/**
 * @file
 * Mark-a-Spot Archive module.
 * This module implements hook_cron to automatically archive reports
 * after a certain period
 */

/**
 * Implements hook_cron().
 */
function markaspot_archive_cron() {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->propertyCondition('status', 1)
    ->propertyCondition('type', array('report'))
    ->propertyOrderBy('created', 'DESC');
  $result = $query->execute();

  $nodes = node_load_multiple(array_keys($result['node']));

  $period = variable_get('archive_days') * 86400;

  foreach ($nodes as $node) {
    if ($node->changed <= time() - $period && $node->field_status['und'][0]['tid'] == 7) {
      $node->field_status['und'][0]['tid'] = "8";
      node_save($node);
    }
  }

}
