<?php
/**
 * @file
 * icon_field.install
 */

/**
 * Implements hook_field_schema().
 */
function icon_field_field_schema($field) {
  return array(
    'columns' => array(
      'bundle' => array(
        'type' => 'varchar',
        'length' => 64,
        'not null' => FALSE,
      ),
      'icon' => array(
        'type' => 'varchar',
        'length' => 64,
        'not null' => FALSE,
      ),
    ),
  );
}
