<?php

/**
 * This module provides styles, scripts and views for Mark-a-Spot Installation
 * and implements some server-side validation and geocoding
 *
 */


function markaspot_logic_form_alter(&$form, &$form_state, $form_id) {
  
  global $user;
  if ($form_id == 'report_node_form') {
    $form['field_address']['und'][0]['value']['#type'] = "hidden";
    // Registered users' mail will be prefilled
    if (isset($user->mail) && arg(0) == 'node' && arg(1) == 'add'){
      $form['field_e_mail']['und'][0]['value']['#default_value'] = $user->mail;
    }
    $form['#validate'][] = 'markaspot_logic_validate';
  }
}

function markaspot_logic_validate($node, &$form) {

    $mail = $form['values']['field_e_mail']['und'][0]['value'];

    if (!valid_email_address($mail)) {
      form_set_error('field_e_mail', t('Please enter a valid e-mail address.'));
    }
    if (!strstr($form['values']['field_geo']['und'][0]['address']['field'], variable_get('markaspot_city'))) {
      form_set_error('field_geo',t('The string given for "City" is not valid'));
    } else {
      // Fill the address field only, if it's not equal to the initial value
      if ($form['values']['field_geo']['und'][0]['lat'] != variable_get('markaspot_ini_lat')) {
        $form['values']['field_address']['und'][0]['value'] = $form['values']['field_geo']['und'][0]['address']['field'];
      }
    }
   
}


/**
 * Implements hook_node_presave
 *
 */

function markaspot_logic_node_presave($node) {
  // print_r($node->field_geo['und'][0]['address']['field']);
  // $address = explode(",", $node->field_geo[und][0][address][field]);
  // print_r($address);
  // die;
}


function markaspot_logic_css_alter(&$css){
  unset($css['misc/ui/jquery.ui.core.css']);
}

/**
 * Implementation of hook_init()
 *
 * - adds some php information to js
 * - adds css
 * - needs refactoring for leaflet
 * 
 */
 
function markaspot_logic_init() {
  $node = menu_get_object();
  $type = (isset($node)) ? $node->type : null ;
  drupal_add_js(array(
    'mas' => array(
      'markaspot_address' => variable_get('markaspot_address'),
      'markaspot_ini_lat' => variable_get('markaspot_ini_lat'),
      'markaspot_ini_lng' => variable_get('markaspot_ini_lng'),
      'cloudmade_api_key' => variable_get('cloudmade_api_key'),

      'uri' => request_uri(),
      'node_type' => $type,
      //'countVotes' => markaspot_logic_getCountVotes(),
      'params' => $_GET)), 
    'setting'
  );

  drupal_add_js(drupal_get_path('module','markaspot_logic'). '/markaspot_logic.js');



  // Add some css to show which line is output by which script
  if (arg(1)!= 'add' && arg(1) != 'edit'){

    if (variable_get('markaspot_map_type') != 1) {

      drupal_add_js('http://maps.google.com/maps/api/js?sensor=false&amp;region=DE', 'external');
      drupal_add_js(drupal_get_path('module', 'markaspot_logic') . '/js/markerclusterer.js', null);
      drupal_add_js(drupal_get_path('module', 'markaspot_logic') . '/js/mapiconmaker_packed.js', null);
      drupal_add_js(drupal_get_path('module', 'markaspot_logic') . '/js/markers_googlemaps.js', null);
    } else {
      drupal_add_css('http://cdn.leafletjs.com/leaflet-0.4.5/leaflet.css', 'external');
      drupal_add_css('http://cdn.leafletjs.com/leaflet-0.4.5/leaflet.ie.css', array(
        'group' => CSS_THEME,
        'browsers' => array(
          'IE' => 'lte IE 8',
          '!IE' => FALSE
          )
      ));
      drupal_add_css(drupal_get_path('module', 'markaspot_logic') . '/css/MarkerCluster.css');
      drupal_add_css(drupal_get_path('module', 'markaspot_logic') . '/css/MarkerCluster.Default.css');
      drupal_add_css(drupal_get_path('module', 'markaspot_logic') . '/css/MarkerCluster.Default.ie.css', array(
        'group' => CSS_THEME,
        'browsers' => array(
          'IE' => 'lte IE 8',
          '!IE' => FALSE
          )
      ));
      drupal_add_js('http://cdn.leafletjs.com/leaflet-0.4.5/leaflet.js', 'external');
      drupal_add_js(drupal_get_path('module', 'markaspot_logic') . '/js/markers_leaflet.js', null);
      drupal_add_js(drupal_get_path('module', 'markaspot_logic') . '/js/leaflet.markercluster.js', null);
    }
  }
  drupal_add_css(drupal_get_path('module', 'custom') . '/css/custom.css', array(
    'group' => CSS_DEFAULT, 'every_page' => TRUE));
  drupal_add_css(drupal_get_path('module', 'markaspot_logic') . '/css/mas-style.css');
}
 
function markaspot_logic_getCountVotes(){
  $list_items = db_query("(SELECT COUNT(*)as Votes FROM {votingapi_vote})");
  foreach ($list_items as $record) {
     return $record->votes;
  }
}
 

/**
 * Implementation of hook_menu()
 *
 * - Callback to feedback page accessible for all
 * - Menu item for system settings page accessible for admins
 * 
 */
function markaspot_logic_menu() {
  $items = array();

  $items['admin/config/system/mark_a_spot'] = array(
    'title' => 'Mark-a-Spot',
    'description' => 'Basic configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('markaspot_logic_admin_settings'),
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    
  );
   $items['admin/config/system/mark_a_spot/tweets/import'] = array(
    'title' => 'Manual twitter import',
    'type' => MENU_LOCAL_TASK,
    'description' => 'Manual twitter import',
    'page callback' => '_markaspot_tweet311_import_manual',
    'access arguments' => array('administer twitter import'),
    'file' => 'markaspot_tweet311.module',
    'file path' => drupal_get_path('module', 'markaspot_tweet311')
  ); 
  // For translation
  //t('No account yet?');

  return $items;
}





/**
 * System settings form on admin settings page,
 * accessible only by admins via menu access restriction
 * 
 * - Set interval lat and lon default value.
 * 
 * @return unknown
 */
function markaspot_logic_admin_settings() {

  $form = array();
  $form['general'] = array(
    '#type' => 'fieldset', 
    '#title' => t('General'), 
    '#collapsible' => TRUE);
  $form['general']['markaspot_address'] = array(
    '#type' => 'textfield',
    '#title' => t('Initial Address'),
    '#default_value' => variable_get('markaspot_address', _markaspot_logic_defaults('markaspot_address')),
    '#size' => '128',
    '#maxlength' => 128,
    '#description' => t('Insert the initial address'),
  );

  $form['general']['markaspot_city'] = array(
    '#type' => 'textfield',
    '#title' => t('City'),
    '#default_value' => variable_get('markaspot_city', _markaspot_logic_defaults('markaspot_city')),
    '#size' => '16',
    '#maxlength' => 16,
    '#description' => t('Insert the municipality'),
  );

  $form['general']['markaspot_ini_lat'] = array(
    '#type' => 'textfield',
    '#title' => t('Inital Lat'),
    '#default_value' => variable_get('markaspot_ini_lat', _markaspot_logic_defaults('markaspot_ini_lat')),
    '#size' => '16',
    '#maxlength' => 32,
    '#description' => t('Insert the initial latitude'),
  );
  $form['general']['markaspot_ini_lng'] = array(
    '#type' => 'textfield',
    '#title' => t('Inital Lng'),
    '#default_value' => variable_get('markaspot_ini_lng', _markaspot_logic_defaults('markaspot_ini_lng')),
    '#size' => '16',
    '#maxlength' => 32,
    '#description' => t('Insert the initial longitude'),
  );
  $form['types']['markaspot_map_type'] = array(
  '#type' => 'radios', 
  '#title' => t('Map type'), 
  '#default_value' => variable_get('markaspot_map_type', 0), 
  '#options' => array(t('Google Maps'), t('OSM')),
  );
  $form['types']['cloudmade_api_key'] = array (
    '#type' => 'textfield',
    '#title' => t('Cloudmade API Key'),
    '#default_value' => variable_get('cloudmade_api_key'),
    '#description' => t('Insert your API Key here')
  );
  if (module_exists('markaspot_tweet311')){
    $form['twitter'] = array (
      '#type' => 'fieldset',
      '#title' => t('Tweet311 Settings'),
      '#description' => t('Let Twitter-Users sending issues by sending mentions to ').variable_get('markaspot_twittername').'. '.t('Tweet-location should be enabled. ').t('Tweets are applied to category-id by hashtag (#id)')
    );

    $form['twitter']['markaspot_twittername'] = array(
      '#type' => 'textfield',
      '#title' => t('Twitter Name '),
      '#default_value' => variable_get('markaspot_twittername', _markaspot_logic_defaults('markaspot_twittername')),
      '#size' => '16',
      '#maxlength' => 16,
      '#description' => t('Which Twitter-Username will be searched for mentions'),
    );
    $form['twitter']['manual_import'] = array(
      '#markup' => '<p>' . l(t('Manually import tweets'), 'admin/config/system/mark_a_spot/tweets/import') . '</p>',
    );
    $form['twitter']['markaspot_tweetSearch'] = array(
      '#type' => 'radios', 
      '#title' => t('Search in tweets for #hashtags or Service Code'), 
      '#default_value' => variable_get('markaspot_tweetSearch'), 
      '#options' => array(t('Hash'), t('Service Code')),
    );
  }

  return system_settings_form($form);
}


function markaspot_logic_page_alter(&$page) {
  // Add help text to the user login block.
  $page['footer']['system_powered-by'] = array(
    '#weight' => -10, 
    // please be nice, give attribution
    '#markup' => '<span>'.t('Built with <a id="mas-link" href="http://mark-a-spot.org">Mark-a-Spot</a>').'</span>',
  );
}


/**
 * Default texts for text variables that build the feedback page. 
 * Texts that can be configured on the settings page.
 * 
 * @param string $id
 * @return string 
 */
function _markaspot_logic_defaults($id) {
  switch ($id) {
    case 'markaspot_ini_lat':
      return '50.8212596';
    case 'markaspot_ini_lng':
      return '6.8961028'; 
    case 'markaspot_address':
      return 'Pingsdorfer Straße 88, 50321 Brühl, Deutschland';
    // case 'markaspot_zip':
    //   return '50321';
    // case 'markaspot_city':
    //   return 'Brühl';
    // case 'markaspot_country':
    //   return 'Deutschland';
    case 'markaspot_twittername':
      return '@mascity';
    case 'markaspot_ini_tweetSearch':
      return '1';

  } 
}



/**
 * Implements hook_block_info().
 *
 * This hook declares what blocks are provided by the module.
 */

function markaspot_logic_block_info() {

  $blocks['taxonomy_category'] = array(
    // info: The name of the block.
    'info' => t('Mark-a-Spot Categories'),
    'cache' => DRUPAL_CACHE_PER_ROLE, 
  );
  $blocks['taxonomy_status'] = array(
    // info: The name of the block.
    'info' => t('Mark-a-Spot Status'),
    'cache' => DRUPAL_CACHE_PER_ROLE, // default
  );
  $blocks['markaspot_map'] = array(
    // info: The name of the block.
    'info' => t('Mark-a-Spot Reports List (Map View)'),
    'cache' => DRUPAL_CACHE_PER_ROLE, // default
  );
  return $blocks;
}


/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 */
function markaspot_logic_block_view($delta = '') {
  //The $delta parameter tells us which block is being requested.
  switch ($delta) {
    case 'taxonomy_category':
      $block['subject'] = t('Services');
      $block['content'] = markaspot_logic_contents($delta);
    break;
    case 'taxonomy_status':
      $block['subject'] = t('Status');
      $block['content'] = markaspot_logic_contents($delta);
    break;
    case 'markaspot_map':
      $block['subject'] = t('ReportList');
      $block['content'] = markaspot_logic_contents($delta);
    break;
  }
  return $block;
}



/**
 * A module-defined block content function.
 */
function markaspot_logic_contents($which_block) {
  switch ($which_block) {
    case 'taxonomy_category': 
      $list_category  = null;
      $list_category .= '<div class="btn-group dropup"><button class="btn btn-large btn-primary">'.t('Services').'</button>';
      $list_category .= '<button class="btn btn-large btn-primary dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></button>';

      $alter['html'] = TRUE;
      $alter['max_length'] = 25;
      $alter['word_boundary'] = true;
      $alter['ellipsis'] = true;
      $list_category .= '<ul class="dropdown-menu">';


      $taxonomies = taxonomy_get_tree(2, $parent = 0, $max_depth = 1, $load_entities = TRUE);
      foreach ($taxonomies as $term) {
        $list_category .= "\n<li class='marker-category-wrapper'>". l(views_trim_text($alter, $term->name),'taxonomy/term/'.$term->tid, array('attributes' => array('class' => 'map-menue marker-category col-'.$term->field_status_hex['und'][0]['value'], 'id' => 'tax-'.$term->tid))).'</li>';
      }
      $list_category .= '</ul>';
      $list_category .= '</div>';

      return $list_category;
    break;
    case 'taxonomy_status':
      $list_status  = null;
      $list_status .= '<div class="btn-group dropup"><button class="btn btn-large btn-primary">'.t('Status').'</button>';
      $list_status .= '<button class="btn btn-large btn-primary dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></button>';


      $alter['html'] = TRUE;
      $alter['max_length'] = 25;
      $alter['word_boundary'] = true;
      $alter['ellipsis'] = true;
      //views_trim_text($alter, $output); 
      $list_status .= '<ul class="dropdown-menu">';
     
      $taxonomies = taxonomy_get_tree(3, $parent = 0, $max_depth = 1, $load_entities = TRUE);
      foreach ($taxonomies as $term) {
        $list_status .= "\n<li class='marker-status-wrapper'>". l(views_trim_text($alter, $term->name),'taxonomy/term/'.$term->tid, array('attributes' => array('class' => 'map-menue marker-status col-'.$term->field_status_hex['und'][0]['value'], 'id' => 'tax-'.$term->tid))).'</li>';
      }
      $list_status .= '</ul>';
      $list_status .= '</div>';

      return $list_status;
    break;    
    case 'markaspot_map':
      $list_map = null;
      $list_map = '<ul id="markersidebar"></ul>';
      return $list_map;

  }
}





