services:
  markaspot-ui-docker-hub:
    container_name: "ddev-${DDEV_SITENAME}-markaspot-ui-docker-hub"
    image: ${MARKASPOT_UI_BASE_IMAGE:-markaspot/markaspot-ui-base:v2.0.0}
    working_dir: /app
    restart: unless-stopped
    # Adding external_links allows connections to `https://example.ddev.site`,
    # which then can go through `ddev-router`
    external_links:
      - ddev-router:${DDEV_SITENAME}.${DDEV_TLD}
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    expose:
      - "3000"
    environment:
      - NUXT_API_BASE=http://web
      - NUXT_GEOREPORT_API_BASE=http://web
      - GEOREPORT_API_KEY=${GEOREPORT_API_KEY:-}
      - NUXT_PUBLIC_JURISDICTION_ID=${JURISDICTION_ID:-}
      - NUXT_JURISDICTION_ID=${JURISDICTION_ID:-}
      - USE_PROXY="true"
      - NODE_ENV=production
      - HOST=0.0.0.0
      - HTTP_EXPOSE=8040:3000
      - HTTPS_EXPOSE=8040:3000
      - VIRTUAL_HOST=$DDEV_HOSTNAME
