name: Docker Image CI

on:
  push:
    branches: [ 10.6.x-dev ]
  pull_request:
    branches: [ 10.6.x-dev ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            target=production
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/markaspot:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7
