name: Docker Image CI

on:
  push:
    branches: [ 10.6.x-dev, 11.7.x-dev, main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine Tag Name
        id: tag_name
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "TAG_NAME=latest" >> $GITHUB_ENV
          fi
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "Building for branch/tag: ${GITHUB_REF}"

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: ./Dockerfile
          build-args: |
            target=production
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/markaspot:${{ env.TAG_NAME }}
          platforms: linux/amd64,linux/arm64
