name: Docker Image CI

on:
  push:
    branches: [ 10.6.x-dev ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Determine Tag Name
        id: tag_name
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "TAG_NAME=latest" >> $GITHUB_ENV
          fi

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            target=production
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/markaspot:${{ env.TAG_NAME }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
