name: Create Release with Library Zips

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # If PHP dependencies are not relevant, you can remove the steps related to Composer
    - name: Install PHP dependencies
      run: composer install --no-dev

    - name: Zip mapbox-gl library
      run: |
        cd web/libraries/mapbox-gl
        zip -r ../../../../mapbox-gl.zip . -x "*.git*"

    - name: Zip maplibre-gl library
      run: |
        cd web/libraries/maplibre-gl
        zip -r ../../../../maplibre-gl.zip . -x "*.git*"

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' # Specify the Node.js version
    # Release with the zipped libraries
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          mapbox-gl.zip
          maplibre-gl.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

